# Generated by Django 2.0.6 on 2018-06-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50, verbose_name='Film Stock')),
                ('iso', models.CharField(max_length=50, verbose_name='iso')),
                ('film_format', models.CharField(max_length=50, verbose_name='Film Format')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Manufacturer Name')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='mfg',
            field=models.ForeignKey(on_delete='CASCADE', to='shots.Manufacturer'),
        ),
    ]
