# Generated by Django 2.0.6 on 2018-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='iso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
