# Generated by Django 2.0.6 on 2018-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0002_auto_20180616_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(upload_to='shot_upload/')),
                ('film', models.ForeignKey(on_delete='PRESERVE', to='shots.Film')),
            ],
            options={
                'verbose_name': 'Shot',
                'verbose_name_plural': 'Shots',
            },
        ),
    ]
